export const ALL_FURNITURE_MODELS = [
  "bathroomCabinet.glb",
  "bathroomCabinetDrawer.glb",
  "bathroomMirror.glb",
  "bathroomSink.glb",
  "bathroomSinkSquare.glb",
  "bathtub.glb",
  "bear.glb",
  "bedBunk.glb",
  "bedDouble.glb",
  "bedSingle.glb",
  "bench.glb",
  "benchCushion.glb",
  "benchCushionLow.glb",
  "bookcaseClosed.glb",
  "bookcaseClosedDoors.glb",
  "bookcaseClosedWide.glb",
  "bookcaseOpen.glb",
  "bookcaseOpenLow.glb",
  "books.glb",
  "cabinetBed.glb",
  "cabinetBedDrawer.glb",
  "cabinetBedDrawerTable.glb",
  "cabinetTelevision.glb",
  "cabinetTelevisionDoors.glb",
  "cardboardBoxClosed.glb",
  "cardboardBoxOpen.glb",
  "ceilingFan.glb",
  "chair.glb",
  "chairCushion.glb",
  "chairDesk.glb",
  "chairModernCushion.glb",
  "chairModernFrameCushion.glb",
  "chairRounded.glb",
  "coatRack.glb",
  "coatRackStanding.glb",
  "computerKeyboard.glb",
  "computerMouse.glb",
  "computerScreen.glb",
  "desk.glb",
  "deskCorner.glb",
  "doorway.glb",
  "doorwayFront.glb",
  "doorwayOpen.glb",
  "dryer.glb",
  "floorCorner.glb",
  "floorCornerRound.glb",
  "floorFull.glb",
  "floorHalf.glb",
  "hoodLarge.glb",
  "hoodModern.glb",
  "kitchenBar.glb",
  "kitchenBarEnd.glb",
  "kitchenBlender.glb",
  "kitchenCabinet.glb",
  "kitchenCabinetCornerInner.glb",
  "kitchenCabinetCornerRound.glb",
  "kitchenCabinetDrawer.glb",
  "kitchenCabinetUpper.glb",
  "kitchenCabinetUpperCorner.glb",
  "kitchenCabinetUpperDouble.glb",
  "kitchenCabinetUpperLow.glb",
  "kitchenCoffeeMachine.glb",
  "kitchenFridge.glb",
  "kitchenFridgeBuiltIn.glb",
  "kitchenFridgeLarge.glb",
  "kitchenFridgeSmall.glb",
  "kitchenMicrowave.glb",
  "kitchenSink.glb",
  "kitchenStove.glb",
  "kitchenStoveElectric.glb",
  "lampRoundFloor.glb",
  "lampRoundTable.glb",
  "lampSquareCeiling.glb",
  "lampSquareFloor.glb",
  "lampSquareTable.glb",
  "lampWall.glb",
  "laptop.glb",
  "loungeChair.glb",
  "loungeChairRelax.glb",
  "loungeDesignChair.glb",
  "loungeDesignSofa.glb",
  "loungeDesignSofaCorner.glb",
  "loungeSofa.glb",
  "loungeSofaCorner.glb",
  "loungeSofaLong.glb",
  "loungeSofaOttoman.glb",
  "paneling.glb",
  "pillow.glb",
  "pillowBlue.glb",
  "pillowBlueLong.glb",
  "pillowLong.glb",
  "plantSmall1.glb",
  "plantSmall2.glb",
  "plantSmall3.glb",
  "pottedPlant.glb",
  "radio.glb",
  "rugDoormat.glb",
  "rugRectangle.glb",
  "rugRound.glb",
  "rugRounded.glb",
  "rugSquare.glb",
  "shower.glb",
  "showerRound.glb",
  "sideTable.glb",
  "sideTableDrawers.glb",
  "speaker.glb",
  "speakerSmall.glb",
  "stairs.glb",
  "stairsCorner.glb",
  "stairsOpen.glb",
  "stairsOpenSingle.glb",
  "stoolBar.glb",
  "stoolBarSquare.glb",
  "table.glb",
  "tableCloth.glb",
  "tableCoffee.glb",
  "tableCoffeeGlass.glb",
  "tableCoffeeGlassSquare.glb",
  "tableCoffeeSquare.glb",
  "tableCross.glb",
  "tableCrossCloth.glb",
  "tableGlass.glb",
  "tableRound.glb",
  "televisionAntenna.glb",
  "televisionModern.glb",
  "televisionVintage.glb",
  "toaster.glb",
  "toilet.glb",
  "toiletSquare.glb",
  "trashcan.glb",
  "wall.glb",
  "wallCorner.glb",
  "wallCornerRond.glb",
  "wallDoorway.glb",
  "wallDoorwayWide.glb",
  "wallHalf.glb",
  "wallWindow.glb",
  "wallWindowSlide.glb",
  "washer.glb",
  "washerDryerStacked.glb"
];

export function getCategoryFromFileName(fileName: string): string {
  const name = fileName.toLowerCase();
  if (name.includes("chair") || name.includes("lounge") || name.includes("stool")) return "Ghế";
  if (name.includes("table") || name.includes("desk")) return "Bàn";
  if (name.includes("bed")) return "Giường";
  if (name.includes("cabinet") || name.includes("bookcase") || name.includes("fridge") || name.includes("washer") || name.includes("dryer")) return "Tủ/Điện máy";
  if (name.includes("kitchen")) return "Bếp";
  if (name.includes("bathroom") || name.includes("toilet") || name.includes("shower") || name.includes("bathtub")) return "Phòng tắm";
  if (name.includes("lamp")) return "Đèn";
  if (name.includes("plant") || name.includes("rug") || name.includes("pillow") || name.includes("mirror")) return "Trang trí";
  return "Khác";
}

export function getNameFromFileName(fileName: string): string {
  // Loại bỏ .glb và camelCase sang Text
  const baseName = fileName.replace(".glb", "");
  const result = baseName.replace(/([A-Z])/g, " $1");
  return result.charAt(0).toUpperCase() + result.slice(1);
}
